const GEO_URL = "https://geo.datav.aliyun.com/areas_v3/bound/";
const SOLUTION_CODE = {"XtraSafe大胖紫":1,"Quell ST风味大师":2,"Quell ST+MinUp":3};
const SOLUTION_COLOR = {"XtraSafe大胖紫":"#B7A4F3","Quell ST风味大师":"#00B0F0","Quell ST+MinUp":"#FFFF00","无数据":"#D9D9D9"};
let chart, currentRows=[], currentTableRows=[];
let state = {level:"country", code:"100000", name:"全国", province:null, city:null, stack:[]};
const provinceCodeFallback={"北京市":"110000","天津市":"120000","河北省":"130000","山西省":"140000","内蒙古自治区":"150000","辽宁省":"210000","吉林省":"220000","黑龙江省":"230000","上海市":"310000","江苏省":"320000","浙江省":"330000","安徽省":"340000","福建省":"350000","江西省":"360000","山东省":"370000","河南省":"410000","湖北省":"420000","湖南省":"430000","广东省":"440000","广西壮族自治区":"450000","海南省":"460000","重庆市":"500000","四川省":"510000","贵州省":"520000","云南省":"530000","西藏自治区":"540000","陕西省":"610000","甘肃省":"620000","青海省":"630000","宁夏回族自治区":"640000","新疆维吾尔自治区":"650000"};
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function norm(n){return String(n||"").replace("特别行政区","").replace("维吾尔自治区","").replace("壮族自治区","").replace("回族自治区","").replace("自治区","").replace("省","").replace("市","").replace("地区","").replace("盟","").trim()}
function fmt(v){return v===null||v===undefined||v===""?"-":Number(v).toFixed(1)}
function activeSolutions(){return Array.from(document.querySelectorAll(".solution-filter:checked")).map(i=>i.value)}
function dominant(counts){return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0]}
function getRowsForState(){if(state.level==="country")return currentRows;if(state.level==="province")return currentRows.filter(r=>norm(r.province)===norm(state.province));if(state.level==="city")return currentRows.filter(r=>norm(r.province)===norm(state.province)&&norm(r.city)===norm(state.city));return currentRows}
function aggregateByGeo(features, rows, level){const active=activeSolutions();const map={};features.forEach(f=>{const n=f.properties.name;map[norm(n)]={name:n,code:String(f.properties.adcode||f.properties.code||""),total:0,counts:{"XtraSafe大胖紫":0,"Quell ST风味大师":0,"Quell ST+MinUp":0},rows:[]}});rows.forEach(r=>{if(!active.includes(r.primary))return;const key= level==="country"?norm(r.province):level==="province"?norm(r.city):norm(r.district);if(!map[key])return;map[key].total++;map[key].counts[r.primary]++;map[key].rows.push(r)});return Object.values(map).map(x=>{if(x.total===0)return {name:x.name,value:0,code:x.code,total:0,counts:x.counts,rows:[],itemStyle:{areaColor:SOLUTION_COLOR["无数据"]}};const d=dominant(x.counts);return {name:x.name,value:SOLUTION_CODE[d],dominant:d,code:x.code,total:x.total,counts:x.counts,rows:x.rows,itemStyle:{areaColor:SOLUTION_COLOR[d]}}})}
async function loadGeo(code){const url=`${GEO_URL}${code}_full.json`;const res=await fetch(url);if(!res.ok)throw new Error(`地图数据加载失败 ${res.status}: ${url}`);return await res.json()}
async function renderMap(){setStatus("地图加载中...");try{const geo=await loadGeo(state.code);echarts.registerMap(state.code,geo);const rows=getRowsForState();const data=aggregateByGeo(geo.features,rows,state.level);chart.setOption({backgroundColor:"#fff",tooltip:{trigger:"item",formatter:p=>{if(!p.data||p.data.total===0)return `${escapeHtml(p.name)}<br/>暂无匹配数据`;return `<strong>${escapeHtml(p.name)}</strong><br/>主推最多：${escapeHtml(p.data.dominant)}<br/>区域记录数：${p.data.total}<br/>XtraSafe大胖紫：${p.data.counts["XtraSafe大胖紫"]}<br/>Quell ST风味大师：${p.data.counts["Quell ST风味大师"]}<br/>Quell ST+MinUp：${p.data.counts["Quell ST+MinUp"]}<br/><span style="color:#64748b">点击进入下一级</span>`}},visualMap:{type:"piecewise",left:22,bottom:20,pieces:[{value:1,label:"XtraSafe大胖紫",color:SOLUTION_COLOR["XtraSafe大胖紫"]},{value:2,label:"Quell ST风味大师",color:SOLUTION_COLOR["Quell ST风味大师"]},{value:3,label:"Quell ST+MinUp",color:SOLUTION_COLOR["Quell ST+MinUp"]}],outOfRange:{color:SOLUTION_COLOR["无数据"]}},series:[{name:"主推方案",type:"map",map:state.code,roam:true,zoom:1.05,label:{show:true,fontSize:state.level==="city"?10:11,color:"#334155"},itemStyle:{borderColor:"#fff",borderWidth:1,areaColor:SOLUTION_COLOR["无数据"]},emphasis:{itemStyle:{areaColor:"#f97316"}},data}]},true);updatePanels(rows,state.name);updateNav();setStatus(`当前层级：${state.level==="country"?"省级":state.level==="province"?"市级":"区级"}。点击有数据色块进入下一级。`)}catch(e){setStatus(e.message)} }
function updatePanels(rows,title){const counts={"XtraSafe大胖紫":0,"Quell ST风味大师":0,"Quell ST+MinUp":0};rows.forEach(r=>{if(counts[r.primary]!==undefined)counts[r.primary]++});document.getElementById("panelTitle").textContent=title;document.getElementById("levelName").textContent=state.level==="country"?"全国/省级":state.level==="province"?"省内/市级":"市内/区级";document.getElementById("totalCount").textContent=rows.length;document.getElementById("topSolution").textContent=rows.length?dominant(counts):"-";document.getElementById("colorDim").textContent=state.level==="country"?"省级":state.level==="province"?"市级":"区级";const box=document.getElementById("solutionSummary");box.innerHTML="";Object.entries(counts).forEach(([s,n])=>{const d=document.createElement("div");d.className="summary-item";d.style.borderLeftColor=SOLUTION_COLOR[s];d.innerHTML=`<span>${escapeHtml(s)}</span><strong>${n}</strong>`;box.appendChild(d)});updateTable(rows)}
function updateTable(rows){currentTableRows=rows;const tb=document.querySelector("#detailTable tbody");tb.innerHTML="";rows.forEach(r=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${escapeHtml(r.province)}</td><td>${escapeHtml(r.city)}</td><td>${escapeHtml(r.district)}</td><td>${fmt(r.gh)}</td><td>${fmt(r.kh)}</td><td>${fmt(r.tds)}</td><td><span class="color-dot" style="background:${SOLUTION_COLOR[r.primary]||'#ddd'}"></span>${escapeHtml(r.primary)}</td><td><span class="color-dot" style="background:${SOLUTION_COLOR[r.secondary]||'#ddd'}"></span>${escapeHtml(r.secondary)}</td><td>${escapeHtml(r.primaryBasis)}</td>`;tb.appendChild(tr)})}
function updateNav(){document.getElementById("breadcrumb").textContent=state.stack.map(s=>s.name).concat([state.name]).join(" / ");document.getElementById("backBtn").disabled=state.level==="country"}
function setStatus(msg){document.getElementById("statusBar").textContent=msg}
function goHome(){state={level:"country",code:"100000",name:"全国",province:null,city:null,stack:[]};renderMap()}
function goBack(){if(state.stack.length===0)return;const prev=state.stack.pop();state={...prev,stack:state.stack};renderMap()}
function downloadCurrentRows(){const headers=["省份","城市","行政区","GH硬度","KH碱度","TDS","主推方案","次推方案","主推依据"];const lines=[headers.join(",")];currentTableRows.forEach(r=>{lines.push([r.province,r.city,r.district,r.gh,r.kh,r.tds,r.primary,r.secondary,r.primaryBasis].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))});const blob=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${state.name}-water-detail.csv`;a.click();URL.revokeObjectURL(url)}
function bind(){window.addEventListener("resize",()=>chart.resize());document.querySelectorAll(".solution-filter").forEach(i=>i.addEventListener("change",renderMap));document.getElementById("homeBtn").onclick=goHome;document.getElementById("backBtn").onclick=goBack;document.getElementById("downloadBtn").onclick=downloadCurrentRows;chart.on("click",p=>{if(!p.data||!p.data.total)return;if(state.level==="country"){const provFull=p.data.rows[0].province;const code=p.data.code||provinceCodeFallback[provFull];if(!code)return;state.stack.push({...state,stack:[...state.stack]});state={level:"province",code,name:p.name,province:provFull,city:null,stack:state.stack};renderMap()}else if(state.level==="province"){const cityFull=p.data.rows[0].city;const code=p.data.code;if(!code)return;state.stack.push({...state,stack:[...state.stack]});state={level:"city",code,name:p.name,province:state.province,city:cityFull,stack:state.stack};renderMap()}else{updatePanels(p.data.rows,p.name)}})}
function init(){currentRows=window.WATER_DATA||[];chart=echarts.init(document.getElementById("chinaMap"));bind();renderMap()}
init();
