const SOLUTION_CODE={"XtraSafe大胖紫":1,"Quell ST风味大师":2,"Quell ST+MinUp":3};
const SOLUTION_COLOR={"XtraSafe大胖紫":"#B7A4F3","Quell ST风味大师":"#00B0F0","Quell ST+MinUp":"#FFFF00","无数据":"#D9D9D9"};
const MAP_NAME={"北京":"北京","天津":"天津","上海":"上海","重庆":"重庆","河北":"河北","山西":"山西","辽宁":"辽宁","吉林":"吉林","黑龙江":"黑龙江","江苏":"江苏","浙江":"浙江","安徽":"安徽","福建":"福建","江西":"江西","山东":"山东","河南":"河南","湖北":"湖北","湖南":"湖南","广东":"广东","海南":"海南","四川":"四川","贵州":"贵州","云南":"云南","陕西":"陕西","甘肃":"甘肃","青海":"青海","台湾":"台湾","内蒙古":"内蒙古","广西":"广西","西藏":"西藏","宁夏":"宁夏","新疆":"新疆","香港":"香港","澳门":"澳门"};
let chart;let currentRows=[];let currentTableRows=[];
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function normalizeProvince(name){return String(name||"").replace("特别行政区","").replace("维吾尔自治区","").replace("壮族自治区","").replace("回族自治区","").replace("自治区","").replace("省","").replace("市","").trim()}
function mapName(prov){const k=normalizeProvince(prov);return MAP_NAME[k]||k||prov}
function formatNumber(v){return v===null||v===undefined||v===""?"-":Number(v).toFixed(1)}
function getActiveSolutions(){return Array.from(document.querySelectorAll(".solution-filter:checked")).map(i=>i.value)}
function getDominantSolution(counts){return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0]}
function aggregateByProvince(rows){const active=getActiveSolutions();const pm={};rows.forEach(row=>{if(!active.includes(row.primary))return;const key=normalizeProvince(row.province);if(!pm[key])pm[key]={name:mapName(row.province),province:row.province,total:0,counts:{"XtraSafe大胖紫":0,"Quell ST风味大师":0,"Quell ST+MinUp":0},rows:[]};pm[key].total+=1;pm[key].counts[row.primary]+=1;pm[key].rows.push(row)});return Object.values(pm).map(item=>{const dominant=getDominantSolution(item.counts);return {name:item.name,value:SOLUTION_CODE[dominant],dominant,total:item.total,counts:item.counts,rows:item.rows,itemStyle:{areaColor:SOLUTION_COLOR[dominant]}}})}
function init(){currentRows=window.WATER_DATA||[];chart=echarts.init(document.getElementById("chinaMap"));if(!echarts.getMap||!echarts.getMap("china")){document.getElementById("chinaMap").innerHTML='<div class="loading">中国地图脚本加载失败，请检查网络或CDN访问。</div>';return}bindEvents();render()}
function render(){const provinceData=aggregateByProvince(currentRows);const option={backgroundColor:"#fff",tooltip:{trigger:"item",formatter:p=>{if(!p.data)return `${escapeHtml(p.name)}<br/>暂无数据`;const d=p.data;return `<strong>${escapeHtml(p.name)}</strong><br/>主推最多：${escapeHtml(d.dominant)}<br/>区域记录数：${d.total}<br/>XtraSafe大胖紫：${d.counts["XtraSafe大胖紫"]}<br/>Quell ST风味大师：${d.counts["Quell ST风味大师"]}<br/>Quell ST+MinUp：${d.counts["Quell ST+MinUp"]}`}},visualMap:{type:"piecewise",left:24,bottom:24,itemWidth:18,itemHeight:14,textStyle:{color:"#334155"},pieces:[{value:1,label:"XtraSafe大胖紫",color:SOLUTION_COLOR["XtraSafe大胖紫"]},{value:2,label:"Quell ST风味大师",color:SOLUTION_COLOR["Quell ST风味大师"]},{value:3,label:"Quell ST+MinUp",color:SOLUTION_COLOR["Quell ST+MinUp"]}],outOfRange:{color:SOLUTION_COLOR["无数据"]}},series:[{name:"最终主推方案",type:"map",map:"china",roam:true,selectedMode:"single",zoom:1.15,label:{show:true,color:"#334155",fontSize:10},itemStyle:{borderColor:"#fff",borderWidth:1,areaColor:SOLUTION_COLOR["无数据"]},emphasis:{label:{color:"#111827",fontWeight:"bold"},itemStyle:{areaColor:"#f97316"}},data:provinceData}]};chart.setOption(option,true);updateSummary(currentRows,"全国汇总");updateDetailTable(currentRows.slice(0,120),"全国汇总")}
function bindEvents(){window.addEventListener("resize",()=>chart.resize());document.querySelectorAll(".solution-filter").forEach(i=>i.addEventListener("change",render));document.getElementById("resetBtn").addEventListener("click",()=>{chart.dispatchAction({type:"mapUnSelect"});updateSummary(currentRows,"全国汇总");updateDetailTable(currentRows.slice(0,120),"全国汇总")});document.getElementById("downloadBtn").addEventListener("click",downloadCurrentRows);chart.on("click",p=>{if(!p.data||!p.data.rows)return;updateSummary(p.data.rows,p.name);updateDetailTable(p.data.rows,p.name)})}
function updateSummary(rows,title){const counts={"XtraSafe大胖紫":0,"Quell ST风味大师":0,"Quell ST+MinUp":0};rows.forEach(r=>{if(counts[r.primary]!==undefined)counts[r.primary]+=1});const total=rows.length;const top=total?getDominantSolution(counts):"-";document.getElementById("panelTitle").textContent=title;document.getElementById("totalCount").textContent=total;document.getElementById("topSolution").textContent=top;const c=document.getElementById("solutionSummary");c.innerHTML="";Object.entries(counts).forEach(([s,n])=>{const d=document.createElement("div");d.className="summary-item";d.style.borderLeftColor=SOLUTION_COLOR[s];d.innerHTML=`<span>${escapeHtml(s)}</span><strong>${n}</strong>`;c.appendChild(d)})}
function updateDetailTable(rows,title){currentTableRows=rows;document.getElementById("panelTitle").textContent=title;const tbody=document.querySelector("#detailTable tbody");tbody.innerHTML="";rows.forEach(row=>{const pc=SOLUTION_COLOR[row.primary]||"#ddd";const sc=SOLUTION_COLOR[row.secondary]||"#ddd";const tr=document.createElement("tr");tr.innerHTML=`<td>${escapeHtml(row.province)}</td><td>${escapeHtml(row.city)}</td><td>${escapeHtml(row.district)}</td><td>${formatNumber(row.gh)}</td><td>${formatNumber(row.kh)}</td><td>${formatNumber(row.tds)}</td><td><span class="color-dot" style="background:${pc}"></span>${escapeHtml(row.primary)}</td><td><span class="color-dot" style="background:${sc}"></span>${escapeHtml(row.secondary)}</td><td>${escapeHtml(row.primaryBasis)}</td>`;tbody.appendChild(tr)})}
function downloadCurrentRows(){const headers=["省份","城市","行政区","GH硬度","KH碱度","TDS","主推方案","次推方案","主推依据"];const lines=[headers.join(",")];currentTableRows.forEach(row=>{const vals=[row.province,row.city,row.district,row.gh,row.kh,row.tds,row.primary,row.secondary,row.primaryBasis].map(v=>`"${String(v??"").replaceAll('"','""')}"`);lines.push(vals.join(","))});const blob=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="water-map-current-detail.csv";document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url)}
init();
